name: Publish Release to npmjs

on:
  push:
    tags:
      - ams-v**

permissions:
  contents: read
  id-token: write

jobs:
  publish-npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: 'https://registry.npmjs.org'

      - name: setup npm for trusted publishing
        run: npm install -g npm@11.5.1
      
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Get the version
        id: get_version
        run: echo "VERSION=$(echo ${GITHUB_REF##*/} | cut -d v -f 2)" >> $GITHUB_OUTPUT
      
      - run: npm ci --no-audit
      
      - run: npm run compile
      
      - run: npm test
      
      - run: npm publish
      
      - name: Update Embedded Player
        if: success()
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_COMMUNICATION }}" \
          https://api.github.com/repos/ant-media/StreamApp/actions/workflows/update-embedded-player.yml/dispatches \
          -d '{"ref":"master"}'



